#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/fontplate_1_00.jar:$APPDIR/lib/core.jar:$APPDIR/lib/batikfont.jar:$APPDIR/lib/geomerative.jar:$APPDIR/lib/itext.jar:$APPDIR/lib/pdf.jar" fontplate_1_00
